#!/bin/sh
#
#   Copyright © 2024 Christopher Augustus
#
#   This Source Code Form is subject to the terms of the Mozilla Public
#   License, v. 2.0. If a copy of the MPL was not distributed with this
#   file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
DYALOG=$(which dyalogscript.bash)
if [ "$DYALOG" = "" ]; then
    echo "Dyalog must be installed."
    echo "A free non-commerical version can be obtained at"
    echo "https://dyalog.com/download-zone.htm"
    exit 1
fi
$DYALOG bbhw.apls $@
