#!/bin/sh
GUILE=$(which guile)
if [ "$GUILE" = "" ]; then
    case $(uname) in
        Darwin)
            echo "Install guile, see e.g. https://formulae.brew.sh/formula/guile"
            ;;
        *)
            echo "Install guile on your system, see https://www.gnu.org/software/guile/download/"
            ;;
    esac
    exit 1
fi
$GUILE --no-auto-compile --r7rs bbhw.scm "$@"
