#!/bin/sh
GUILE=$(which guile)
if [ "$GUILE" = "" ]; then
  PATH_HERE=$(pwd)/$(dirname $0)
  PATH_BUILD="$PATH_HERE/build"
  PATH_INSTALL="$PATH_HERE/guile"
  GUILE="$PATH_INSTALL/bin/guile"
  if [ ! -f $GUILE ]; then
    mkdir -p "$PATH_BUILD"
    pushd "$PATH_BUILD"

    # libunistring: gettext and Guile dependency
    curl -s https://ftp.gnu.org/gnu/libunistring/libunistring-1.2.tar.gz | tar zxvf -
    pushd libunistring-1.2
    ./configure --prefix="$PATH_INSTALL" --disable-debug --disable-docs
    make -j4
    make install
    popd

    # gettext: pkg-config and Guile dependency
    curl -s https://ftp.gnu.org/pub/gnu/gettext/gettext-0.22.5.tar.gz | tar zxvf -
    pushd gettext-0.22.5
    ./configure --prefix="$PATH_INSTALL" \
                --with-included-glib \
                --with-included-libxml \
                --disable-java \
                --disable-csharp \
                --without-git \
                --without-cvs \
                --without-xz \
                --disable-debug \
                --disable-docs
    make -j4
    make install
    popd

    # pkg-config: Guile dependency
    curl -s https://pkg-config.freedesktop.org/releases/pkg-config-0.29.2.tar.gz | tar zxvf -
    pushd pkg-config-0.29.2
    # See https://gitlab.freedesktop.org/pkg-config/pkg-config/-/issues/81
    CFLAGS="-Wno-int-conversion" CXXFLAGS="-Wno-int-conversion" ./configure \
          --prefix="$PATH_INSTALL" \
          --with-internal-glib \
          --disable-host-tool \
          --disable-debug \
          --disable-docs
    make -j4
    make install
    popd

    # bdw-gc: Guile dependency
    curl -s https://www.hboehm.info/gc/gc_source/gc-8.2.4.tar.gz | tar zxvf -
    pushd gc-8.2.4
    ./configure --prefix="$PATH_INSTALL" --disable-debug --disable-docs
    make -j4
    make install
    popd

    # libffi: Guile dependency
    curl -sL https://github.com/libffi/libffi/releases/download/v3.4.6/libffi-3.4.6.tar.gz | tar zxvf -
    pushd libffi-3.4.6
    ./configure --prefix="$PATH_INSTALL" --disable-debug --disable-docs
    make -j4
    make install
    popd

    # Guile itself
    curl -s https://ftp.gnu.org/gnu/guile/guile-3.0.10.tar.gz | tar zxvf -
    pushd guile-3.0.10
    PKG_CONFIG="$PATH_INSTALL/bin/pkg-config" PKG_CONFIG_LIBDIR="$PATH_INSTALL/lib/pkgconfig" ./configure \
      --prefix="$PATH_INSTALL" \
      --with-bdw-gc="$PATH_INSTALL"/lib/pkgconfig/bdw-gc.pc \
      --with-libunistring-prefix="$PATH_INSTALL" \
      --enable-mini-gmp
    make -j4
    make install
    popd

    popd
  fi
fi
$GUILE --no-auto-compile --r7rs bbhw.scm "$@"
