#!k
//
//  Copyright © 2024 Christopher Augustus
//
//  This Source Code Form is subject to the terms of the Mozilla Public
//  License, v. 2.0. If a copy of the MPL was not distributed with this
//  file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
//  https://code.golf/zeckendorf-representation#k
//
`0:"\n"/{3_""{" + "/(x;$y)}/1_{$[z>(+/x)+y;x,y;x]}/[0;|1_+\[46;0;1];1+.x]}\:(2_`argv[])
