#! /bin/bash
if ! which chpl >& /dev/null ; then
  if ! [ -f chapel-*/util/quickstart/setchplenv.bash ] ; then
    ./get
  fi
  . chapel-*/util/quickstart/setchplenv.bash >& /dev/null
fi
if [ bbhw.chpl -ot bbhw ] || chpl bbhw.chpl ; then
  ./bbhw "$@"
fi
