#! /bin/bash
if ! which -s chpl ; then
  if ! [ -f chapel-*/util/quickstart/setchplenv.bash ] ; then
    ./get
  fi
  . chapel-*/util/quickstart/setchplenv.bash
fi
if [ bbhw.chpl -ot bbhw ] || chpl bbhw.chpl ; then
  ./bbhw "$@"
fi
