#!/bin/sh
#
#   Copyright © 2024 Christopher Augustus
#
#   This Source Code Form is subject to the terms of the Mozilla Public
#   License, v. 2.0. If a copy of the MPL was not distributed with this
#   file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
GAMBIT=$(which gsi)
if [ "$GAMBIT" = "" ]; then
  PATH_HERE=$(pwd)/$(dirname $0)
  PATH_REPO="$PATH_HERE/gambit"
  GAMBIT="$PATH_REPO/gsi/gsi"
  if [ ! -f $GAMBIT ]; then
    if [ ! -d $PATH_REPO ]; then
      git clone -v git@github.com:aboalang/gambit
    fi
    cd $PATH_REPO
    git checkout v4.9.5
    ./configure --prefix $PATH_REPO
    make -j4
    cd $PATH_HERE
  fi
fi
$GAMBIT bbhw.scm $@
