#!/bin/sh
#
#   Copyright © 2024 Christopher Augustus
#
#   This Source Code Form is subject to the terms of the Mozilla Public
#   License, v. 2.0. If a copy of the MPL was not distributed with this
#   file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
BQN=$(which bqn)
if [ "$BQN" = "" ]; then
    PATH_HERE=$(pwd)/$(dirname $0)
    PATH_REPO="$PATH_HERE/cbqn"
    BQN="$PATH_REPO/BQN"
    if [ ! -f $BQN ]; then
        if [ ! -d $PATH_REPO ]; then
            git clone -v git@github.com:aboalang/cbqn
        fi
        cd $PATH_REPO
        git checkout v0.6.0
        make
        cd $PATH_HERE
    fi
fi
$BQN -s -f bbhw.bqn $@
